# TODO:
# - Introduce .env file for configurations
services:
  neurowolf:
    extends:
      file: ./dockerfiles/ai/base.yml
      service: igpu_ollama
    container_name: neurowolf
    environment:
      - LLM_MODEL=hf.co/attashe/gemma-2-9b-it-russian-function-calling-GGUF-Q8_0-GGUF
      - LLM_QUANT=
      - TELEGRAM_BOT_TOKEN
    volumes:
      - ./:/app:ro
