# TODO:
# - Introduce .env file for configurations
services:
  neurowolf:
    extends:
      file: ./dockerfiles/ai/base.yml
      service: igpu_ollama
    container_name: neurowolf
    environment:
      - LLM_MODEL=hf.co/KoLLchIK/DeepSeek-R1-Distill-Qwen-1.5B-Russian_dataset
      - LLM_QUANT=Q8_0
    volumes:
      - ./:/app:ro
